/**
 * Liste des bureaux Yalidine (stop desks) — source: yalidine.com/nos-agences
 * Utilisée en secours quand l'API Yalidine ne renvoie pas de liste.
 * Format: { id, name, address, wilaya } avec wilaya = code (01, 16, etc.)
 */

const WILAYA_NAME_TO_CODE = {
  Adrar: '01',
  Chlef: '02',
  Laghouat: '03',
  'Oum El Bouaghi': '04',
  Batna: '05',
  Béjaïa: '06',
  Biskra: '07',
  Béchar: '08',
  Blida: '09',
  Bouira: '10',
  Tamanrasset: '11',
  Tébessa: '12',
  Tlemcen: '13',
  Tiaret: '14',
  'Tizi Ouzou': '15',
  Alger: '16',
  Djelfa: '17',
  Jijel: '18',
  Sétif: '19',
  Saïda: '20',
  Skikda: '21',
  'Sidi Bel Abbès': '22',
  'Sidi Bel Abbes': '22',
  Annaba: '23',
  Guelma: '24',
  Constantine: '25',
  Médéa: '26',
  "M'Sila": '28',
  Mascara: '29',
  Ouargla: '30',
  Oran: '31',
  'El Bayadh': '32',
  Illizi: '33',
  'Bordj Bou Arréridj': '34',
  'Bordj Bou Arreridj': '34',
  Boumerdès: '35',
  Boumerdes: '35',
  'El Tarf': '36',
  Tindouf: '37',
  Tissemsilt: '38',
  'El Oued': '39',
  Khenchela: '40',
  'Souk Ahras': '41',
  Tipaza: '42',
  Mila: '43',
  'Aïn Defla': '44',
  Naâma: '45',
  "Aïn Témouchent": '46',
  Ghardaïa: '47',
  Relizane: '48',
  "El M'Ghair": '49',
  'El Meniaa': '50',
  'El Menia': '50',
  'Ouled Djellal': '51',
  Timimoun: '54',
  Touggourt: '55',
  Djanet: '56',
  'In Salah': '57',
}

// [id, wilayaName, name, address]
const BUREAUX_RAW = [
  [10101, 'Adrar', 'Agence de Adrar [Yalidine]', 'Rue Benhachem Maamar'],
  [21101, 'Chlef', 'Agence de Chlef [Yalidine]', 'Route national N4 Chlef'],
  [21102, 'Chlef', 'Agence de Chlef [Guepex]', 'Cité Cherifi Kadour, 113'],
  [21103, 'Chlef', 'Agence Hay El Nasr [Zimou-Express]', "Hay El Nasr, Zone 04 (A coté de l'arrêt de bus)"],
  [23401, 'Chlef', 'Agence de Ténès [Guepex]', 'Bt A2 Rdc Local 28, Sortie Ouest Route De Mostaganem'],
  [31901, 'Laghouat', 'Agence de Aflou [Yalidine]', 'Hai Zahi Ben Aissa, Route El Bayadh'],
  [30102, 'Laghouat', 'Agence Laghouat (Cité OASIS)', "Cité l'OASIS, centre ville Laghouat"],
  [40301, 'Oum El Bouaghi', "Agence de Aïn M'lila [Yalidine]", 'Route Messas (à coté superette Amiche)'],
  [40101, 'Oum El Bouaghi', 'Agence de Oum el Bouaghi [Yalidine]', 'Cité El Moustakbel'],
  [54201, 'Batna', 'Agence de Barika [Guepex]', 'Boulevard Azil Abdul Rahman, Route De Batna'],
  [50101, 'Batna', 'Agence des 500 Logements [Yalidine]', 'Lotissement Meddour (En Face Lycee 500 Logements)'],
  [50103, 'Batna', 'Agence du CHU Route de Tazoult [Guepex]', 'Cité frères Lombarkia, ex parc à fourrage'],
  [62501, 'Béjaïa', 'Agence de Akbou [Yalidine]', 'Cite 16 Logement Eplf'],
  [60101, 'Béjaïa', 'Agence de Béjaïa (Cité Tobal) [Guepex]', 'Cité Tobal en face de Syken collège, Béjaïa'],
  [60102, 'Béjaïa', 'Agence de Béjaïa (Edimco) [Yalidine]', 'Zone Industrielle, Rue Mahfoudi Fateh, Edimco'],
  [64001, 'Béjaïa', 'Agence de El Kseur [Guepex]', "Rue Zema Abdelkader, commune d'El Ksar"],
  [70402, 'Biskra', 'Agence de Biskra (Zone Ouest)', 'Coopératif du verger N°22 Zone Ouest, Biskra'],
  [73201, 'Biskra', 'Agence de Tolga [Guepex]', 'Cité Sidi Rouak rue Soltani Ahmed'],
  [80101, 'Béchar', 'Agence de Béchar (Centre Ville) [Yalidine]', 'Cite Hai El Badr, Lot N°50, Béchar'],
  [80102, 'Béchar', 'Agence Béchar (Cité Es Salam)', 'Quartier Essalam, Section 21, Béchar'],
  [90101, 'Blida', 'Agence de Blida [Yalidine]', 'Zone industrielle Ben Boulaid (Devant Family Shop)'],
  [90102, 'Blida', 'Agence de Bab Dzair [Guepex]', "21 centre d'artisans, rue d'Alger"],
  [92001, 'Blida', 'Agence de Boufarik [Guepex]', '64 Rue Si Ben Youcef'],
  [92101, 'Blida', 'Agence de Larbaa [Zimou-Express]', 'Rue El Emir Khaled'],
  [91601, 'Blida', 'Agence Mouzaia Blida [Guepex]', 'Quartier du marché groupe 36'],
  [90701, 'Blida', 'Agence Ouled Yaich [Yalidine]', 'Rue de la mosquée'],
  [100101, 'Bouira', 'Agence Ain Bessem [Guepex]', 'Rue Abdelkader Bouziane, Aïn Bessem'],
  [101601, 'Bouira', 'Agence de Bouira [Yalidine]', "Lotissement Amar Khoudja B0 (Nouveau Rond Point D'Aigle)"],
  [103101, 'Bouira', 'Agence de Lakhdaria [Yalidine]', "Cité si Lakhdar Derrière l'Algérienne des Eaux"],
  [104101, 'Bouira', 'Agence de Sour El Ghouzlane [Guepex]', 'N°03 Cite Sayeh, Section 13'],
  [110101, 'Tamanrasset', 'Agence de Tamanrasset (Gataâ El Oued) [Guepex]', 'Cité Gataâ El Oued N 742 743'],
  [110102, 'Tamanrasset', 'Agence Tamanrasset (Tahaggart) [Yalidine]', 'Tahaggart CHARKIA EN FACE MOSQUEE F.ZAHRAA'],
  [110103, 'Tamanrasset', 'Agence Tamanrasset (Sorro Ivolutif)', 'حي سورو بلدية تامنراست'],
  [120301, 'Tébessa', 'Agence Cheria Tébessa [Guepex]', 'رقم 10مكرر التحصيص البلدي رقم 02'],
  [120101, 'Tébessa', 'Agence de Tébessa [Yalidine]', 'Boulevard Houari Boumediene (En Face De La Pharmacie Hazourli)'],
  [120103, 'Tébessa', 'Centre de tri Skanska (Tébessa) [Yalidine]', 'Cité El Amel, Skanska, Tébessa'],
  [135001, 'Tlemcen', 'Agence Chetouane [Yalidine]', 'Zone industrielle'],
  [132701, 'Tlemcen', 'Agence de Maghnia [Yalidine]', "Tafna N°4 Cite Perri"],
  [130401, 'Tlemcen', 'Agence Remchi [Yalidine]', 'Rue Adjedir Mohamed'],
  [130101, 'Tlemcen', 'Agence de Tlemcen (Bel-Air) [Guepex]', 'Quartier Mohammed 05- BEL-AIR'],
  [130103, 'Tlemcen', 'Agence de Tlemcen (Mansourah) [Yalidine]', 'Boulevard Imama (en face la piscine olympique)'],
  [143901, 'Tiaret', 'Agence de Tiaret [Yalidine]', 'Rue police Amer, n 161'],
  [151801, 'Tizi Ouzou', 'Agence de Azazga [Yalidine]', '01 Rue Djurdjura, Immeuble Ait Amara'],
  [153201, 'Tizi Ouzou', 'Agence Beni Douala [Yalidine]', 'Beni Douala'],
  [154701, 'Tizi Ouzou', 'Agence de Draâ Ben Khedda [Guepex]', 'Touares 01'],
  [151101, 'Tizi Ouzou', 'Agence de Tizi Gheniff [Guepex]', 'Rue Fatoum Amar, Rez-De-Chaussee Btm 17, N° 02'],
  [150101, 'Tizi Ouzou', 'Agence de Bekkar [Guepex]', 'Cite Bekkar Classe 78 (En Face Placette)'],
  [150102, 'Tizi Ouzou', 'Agence de Nouvelle Ville [Yalidine]', 'Nouvelle ville'],
  [164401, 'Alger', 'Agence de Aïn Benian [Guepex]', '19 Route Al-Jamilah, Division Kargon'],
  [160101, 'Alger', 'Sacré-Cœur [Guepex]', '116 Didouche Mourad, Sacre Cœur'],
  [160501, 'Alger', 'Agence de Bab El Oued [Guepex]', '107 Rue Colonel Lotfi'],
  [162102, 'Alger', 'Agence Bab Ezzouar [Yalitec]', 'EPLF - BAB EZZOUAR'],
  [161601, 'Alger', 'Agence Bachdjerrah', "Bachdjerrah 3 derrière l'ancien APC, à 80 m du métro"],
  [161401, 'Alger', 'Agence de Baraki [Guepex]', "Route de Larbâa (à coté de la supérette Promo+)"],
  [160902, 'Alger', 'Agence Bir Mourad Rais', '14 rue des trois, Bir Mourad Raïs'],
  [161201, 'Alger', 'Agence de Birkhadem [Yalidine]', 'Cite Vergers Villa N°1'],
  [163401, 'Alger', 'Agence de Birtouta [Guepex]', '06 rue El Moudjahid Hamida Mouhamed'],
  [163901, 'Alger', 'Agence Bordj El Bahri (Café Chergui) [Yalidine]', "Groupe de propriété n°3065, Bordj El Bahri"],
  [163001, 'Alger', 'Agence de Bordj El Kiffan [Yalidine]', 'Rue 1Er Novembre 26 Cite Mimouni N 04'],
  [165001, 'Alger', 'Dar Diaf [Yalidine]', 'Dar Diaf (à Côté De La Supérette Sedda)'],
  [165002, 'Alger', 'HUB Cheraga (Plateau) [Yalidine]', '10, Rue Aïn Benian Partie: 192 C2, Cheraga'],
  [162003, 'Alger', "Agence d'El Hamiz", "Cité les orangers Groupe A villa N°431, El Hamiz"],
  [162602, 'Alger', 'Agence Gué de Constantine [SpeedMail]', 'Cite Sonelgaz 2 Villa 184 Alger'],
  [165301, 'Alger', 'Agence de Draria [Guepex]', 'Cite Darbush 145, Habitation 400, Batiment 2'],
  [161701, 'Alger', 'Hussein Dey [Yalidine]', 'Route Tripoli N°152'],
  [163302, 'Alger', 'Agence Les Eucalyptus [Zimou-Express]', 'Rue Les Eucalyptus, N°56, palais rouge'],
  [164701, 'Alger', 'Agence de Sidi Abdellah [Zimou-Express]', 'Cité 1400 local C6 Bt C6 sidi Abdallah'],
  [162902, 'Alger', 'Agence les Pins Maritime [Yalitec]', 'Rue Les Pins Maritime Alger'],
  [161503, 'Alger', 'Agence El Harrach (Beaulieu)', '128 RUE BOUBAGHLA Beaulieu - OUED SEMAR'],
  [165101, 'Alger', 'Agence de Ouled Fayet [Guepex]', '19 route du stade communal'],
  [164301, 'Alger', 'Agence de DNC [Yalidine]', 'Cité El Ouancharis, DNC, Route de Ain Taya'],
  [164201, 'Alger', 'Agence de Rouiba [Zimou-Express]', 'Rue Hassiba Ben Bouali'],
  [164601, 'Alger', 'Agence de Zeralda [Guepex]', 'Cite Yesswel Kouider N°01'],
  [170501, 'Djelfa', "Agence de Aïn Oussara [Yalidine]", "Cité Mohamed Boudiaf (rue en face la BNA)"],
  [171401, 'Djelfa', 'Agence de Djelfa [Yalidine]', 'Cité Boutrifis, route de Boussaâda, lotissement 137 N 06'],
  [180901, 'Jijel', 'Agence de El Milia [Guepex]', 'Rue Boulakirba Zidane'],
  [180101, 'Jijel', 'Agence de Jijel [Yalidine]', 'Village Mustapha RDC ROUTE SOUMMAM N°24'],
  [181401, 'Jijel', 'Agence Kaous (Jijel) [Yalidine]', 'Cité Amoura Messouad N°02 Commune Kaous'],
  [180501, 'Jijel', 'Agence de Taher [Guepex]', 'Immeuble Des Bailleurs, Section 58, Quartier Zemouch'],
  [190701, 'Sétif', 'Agence de Aïn Oulmene [Guepex]', 'Cite 113, Immeuble Residentiel 63, Batiment 1'],
  [192601, 'Sétif', 'Agence de Bougaa [Guepex]', 'Rue Mohamed Chinoune'],
  [193202, 'Sétif', 'Desk El Eulma [Yalidine]', 'Rue Abdelaziz Khaled, n°119'],
  [193203, 'Sétif', 'Agence El Eulma Cité Sonatrach Smara S', 'Smara Sud, Section 14, El Eulma'],
  [195501, 'Sétif', 'Agence Maabouda [Yalidine]', "Cite D'Al-Ma'Bouda, Escalier 1 Du Batiment B"],
  [195502, 'Sétif', 'Agence El Hidhab [Guepex]', 'Cité El Hidhab, 110 Logements Participatifs'],
  [201101, 'Saïda', 'Agence de Saïda [Yalidine]', 'Cité Riadh (à coté de la mosquée Riadh)'],
  [210501, 'Skikda', 'Agence de Azzaba [Guepex]', 'Enseigne Cite Za\'Af Rabeh'],
  [211401, 'Skikda', 'Agence de Collo [Guepex]', 'Boulevard Ruwaibah Taher'],
  [211801, 'Skikda', 'Agence de El Harrouch [Guepex]', 'Cite 24 Logements Sociaux Covalent Sonatiba'],
  [213501, 'Skikda', 'Centre de tri et Agence Messiouen (Skikda) [Yalidine]', '30 logement Bt 02 Rue de Chaussée Skikda'],
  [213502, 'Skikda', 'Nouvelle Agence Skikda L\'espérance [Yalidine]', 'Rue El Reboua El Djamila'],
  [213503, 'Skikda', 'Agence de Skikda Faubourg [Guepex]', 'Rue Bachir BOUKADOUM BT 06 local N° 1'],
  [223601, 'Sidi Bel Abbès', 'Agence Sidi Bel Abbès [Yalidine]', 'Rue Mascara, (à cote de l\'hotel Beni Talla)'],
  [223602, 'Sidi Bel Abbès', 'Agence Sidi Bel Abbès (Benhamouda) [Guepex]', 'Benhamouda, Sidi Bel Abbès'],
  [230101, 'Annaba', 'Agence de Valmascort [Yalidine]', 'Avenue Seddik Benyahia Résidence Fadi el Djamal'],
  [230102, 'Annaba', 'Agence de Sidi Brahim [Guepex]', 'Champs de mars numéro n°3'],
  [230103, 'Annaba', 'Agence Sidi Achour GHANZOH EXPRESS', 'Rte de Sidi Achour, Annaba'],
  [230501, 'Annaba', 'Agence de El Bouni [Guepex]', 'Section 1 Groupe 63 Propriete 246'],
  [241901, 'Guelma', 'Nouvelle Agence Guelma [Yalidine]', 'Route Ain Larbi, local N°01'],
  [243001, 'Guelma', 'Agence de Oued Zenati [Guepex]', 'Magasin Num 02'],
  [250401, 'Constantine', 'Agence Belle Vue [Yalidine]', '70 Rue Belle Vue, Les Combattants'],
  [250402, 'Constantine', 'Agence Sidi Mabrouk [Guepex]', 'نهج لعراقب احمد رقم 09'],
  [250403, 'Constantine', 'Agence de Constantine Zouaghi [Zimou Express]', 'Illot N°01, 212, ain el bay, zouaghi'],
  [250501, 'Constantine', 'Agence de Didouche Mourad [Yalidine]', 'El Riadh n°10'],
  [250601, 'Constantine', "Agence d'El Khroub [Guepex]", 'Cité Bouhali Mohamed Said El Khroub'],
  [250602, 'Constantine', 'Agence Nouvelle ville Ali Mendjeli [Yalidine]', "Zone d'Activité N°47 Nouvelle Ville, Ali MENDJLI"],
  [250605, 'Constantine', 'Agence Nouvelle Ville [Guepex]', '650 lpa عمارة 24 زاوية محل 145'],
  [260701, 'Médéa', 'Agence Médéa (Beni Slimane) [Yalidine]', 'بني سليمان'],
  [263301, 'Médéa', 'Agence de Médéa (El Koutab) [Yalidine]', 'Hai El Koutab Médéa (En face boutique Dyelna Shop)'],
  [263302, 'Médéa', 'Agence de Médéa (Pole Urbain) [Guepex]', 'Cité 80 Logs LSP Pole Urbain'],
  [265901, 'Médéa', 'Agence Tablat [Yalidine]', 'Rue Nationale N°08, Tablat, Médéa'],
  [271801, 'Mostaganem', 'Salamandre [Yalidine]', 'Salamandre (Rond Point De La Douane)'],
  [271802, 'Mostaganem', 'Kharouba [Guepex]', 'Cité 600 logement Kharouba Mostaganem'],
  [281001, 'M\'Sila', 'Agence de Berhoum [Guepex]', 'حي زيغود يوسف بلدية برهوم'],
  [281201, 'M\'Sila', 'Agence de Bou Saâda [Yalidine]', 'Cite 20 Aout 636/N°05 A'],
  [282802, 'M\'Sila', 'Agence Salem Shopping Mall [Yalidine]', 'Salem Shopping Mall, centre commercial'],
  [283901, 'M\'Sila', 'Agence Sidi Aïssa [Guepex]', 'بلدية سيدي عيسى'],
  [292801, 'Mascara', 'Agence de Mascara [Yalidine]', 'Zone 08 à coté de la poste Emir Abdelkader'],
  [300801, 'Ouargla', 'Agence de Hassi Messaoud [Yalidine]', "Derrière la CNAS, à coté de la clinique Ibn Sina"],
  [301301, 'Ouargla', 'Agence de Ouargla Centre Ville [Guepex]', 'حي حركات'],
  [301302, 'Ouargla', 'Agence de Ouargla (Chetti el Wekal) [Yalidine]', 'Ave 1er novembre 1954, El Mkhadma'],
  [310601, 'Oran', 'Agence de Arzew [Guepex]', '17 Lotissement N 66 Plan Lot 167'],
  [310301, 'Oran', 'El Morchid [Yalidine]', 'Cooperative Immobiliere Dar El Amel N°68'],
  [310302, 'Oran', 'Agence Fernand Ville [Yalidine]', '65 Rue 1er Novembre Hai Khemisti'],
  [310303, 'Oran', 'Agence ILAF Belkaïd Oran', 'Groupe 122 Logement - résidence ILAF Belkaïd'],
  [310102, 'Oran', 'Cité Djamel [Guepex]', 'Rond-point cité Djamel (en allant vers Hai Sabah)'],
  [310103, 'Oran', 'Agence de Gambetta [Zimou-Express]', '54 avenue d\'arcole, Bouguerri Khelifa, Gambetta'],
  [310104, 'Oran', 'Agence Canastel [SpeedMail]', '25, Rue Akid Lotfi Local N° 02'],
  [320101, 'El Bayadh', 'Agence de El Bayadh [Yalidine]', 'Rue Mohamed Touil (A Cote Auberge Hanna)'],
  [330101, 'Illizi', 'Agence de Illizi [Guepex]', 'Chemin Ain El Kours Cite Salam'],
  [330601, 'Illizi', 'Agence In Amenas [Guepex]', 'ان اميناس'],
  [340601, 'Bordj Bou Arréridj', 'Agence BBA [Yalidine]', 'Cite 17 octobre rue ameur tahar N°5'],
  [340603, 'Bordj Bou Arréridj', 'Agence BBA Nouveau Lycée [Guepex]', 'بورج بوعريريج'],
  [350501, 'Boumerdès', 'Agence de Bordj Menaiel [Guepex]', 'Rue Bouira Boualem, Section 02 Magasin 02'],
  [350201, 'Boumerdès', 'Agence Boudouaou [Guepex]', 'بن عجال بودواو ولاية بومرداس'],
  [350101, 'Boumerdès', 'Agence de Boumerdès [Yalidine]', 'Cité Foés bâtiment B local N°04'],
  [353601, 'Boumerdès', 'Agence Hammedi', 'Hammedi centre ville'],
  [361301, 'El Tarf', 'Agence Dréan El Tarf [Yalidine]', 'Rue lmzaouda al-arbi el dréan'],
  [361701, 'El Tarf', 'Agence de El Tarf [Yalidine]', 'Rue N°44 Cite Les Vergers'],
  [370201, 'Tindouf', 'Agence de Tindouf [Yalidine]', 'Cites Moussani (A Cote De La Radio)'],
  [382101, 'Tissemsilt', 'Agence de Tissemsilt [Yalidine]', 'Rue Bouis Ali Num 33 B Section 067'],
  [390101, 'El Oued', 'Agence de El Oued [Yalidine]', 'Cite El Moudjahidine (en face Pharmacie Daghoum)'],
  [401302, 'Khenchela', 'Agence route de Meskiana [Yalidine]', 'Route de Meskiana N°30 lot 66 Khenchela'],
  [410101, 'Souk Ahras', 'Agence de Souk Ahras [Yalidine]', 'Cité El Louz Lot 64 (les amandiers)'],
  [422201, 'Tipaza', 'Agence Cherchell [Guepex]', 'N°05 Rue MELHANI ABDERRAHMAN'],
  [421201, 'Tipaza', 'Agence Hadjout (Rue de stade)', 'Rue de stade RDC Hadjout, Tipaza'],
  [423501, 'Tipaza', 'Agence Koléa [Guepex]', 'Koléa, Lotissement Amara N°1 Route de Fouka'],
  [420101, 'Tipaza', 'Agence Tipaza [Yalidine]', "24 cite M'hamed Bougara (El Garari)"],
  [430801, 'Mila', 'Agence de Chelghoum Laid [Yalidine]', "Rue 01 Novembre, A Côté D'Hôtel El Rhumel"],
  [431302, 'Mila', 'Agence Ferdjioua [Guepex]', 'فرجيوة'],
  [431601, 'Mila', 'Centre de tri Mila [Yalidine]', 'Rue De Zerghia'],
  [431602, 'Mila', 'Agence Mila [Yalidine]', 'شارع بن قارة النوار بلدية ميلة'],
  [440101, 'Aïn Defla', 'Agence de Aïn Defla [Guepex]', "Cite Khyat Mohammed (Zone Industrielle)"],
  [442601, 'Aïn Defla', 'Agence de Khemis Miliana [Guepex]', 'Le Cote Ouest Du Quartier La Cadette Route Nationale'],
  [450201, 'Naâma', 'Agence de Mecheria [Guepex]', 'Rue Abdellaoui Mohammed Cité Iben Badis'],
  [460401, 'Aïn Témouchent', 'Agence de Aïn Témouchent [Yalidine]', 'Hai Zitoun (à coté de la nouvelle agence de transport)'],
  [460701, 'Aïn Témouchent', 'Agence de Beni Saf [Guepex]', "Cité Sohbi (en face de la pompe d'essence)"],
  [470201, 'Ghardaïa', 'Agence Bounoura Ghardaia', "Cité Bahman local 07 Route d'el Atteuf"],
  [470701, 'Ghardaïa', 'Agence de Ghardaïa Thenia [Guepex]', 'Ghardaïa Thenia a coté de lycé mofdi zakaria'],
  [470702, 'Ghardaïa', 'Agence de Bouhraoua [Yalidine]', "Bouhraoua (En face centre d'exposition)"],
  [483001, 'Relizane', 'Agence de Relizane [Yalidine]', 'Boulevard 69 Zaghloul (en face la banque d\'Algérie)'],
  [490901, 'Timimoun', 'Agence de Timimoun [Yalidine]', 'Rue Mohamed El Hashemi'],
  [512601, 'Ouled Djellal', 'Agence de Ouled Djellal [Yalidine]', 'Rue Gasmi Ibrahim (En Face Ecole Mazen School)'],
  [530801, 'In Salah', 'Agence de In Salah [Yalidine]', 'Centre ville (à coté de la poste et la maison de jeune)'],
  [552001, 'Touggourt', 'Agence de Touggourt [Yalidine]', 'Cite Rimal 01 (Route Nationale N°03)'],
  [560201, 'Djanet', 'Agence de Djanet [Guepex]', 'Tin Khatma'],
  [572801, 'El M\'Ghair', 'Agence de Djamaa [Guepex]', 'Cite Essalam (A Cote Du Clinique Douaa)'],
  [572701, 'El M\'Ghair', 'Agence de El M\'Ghair [Yalidine]', 'Lotissement 360 Logements Nouvelle Zone Urbaine'],
  [580601, 'El Meniaa', 'Agence de El Menia [Yalidine]', 'Route Unite Africaine'],
]

function getBureauxByWilaya(wilayaCode) {
  let code = String(wilayaCode || '').trim()
  if (code && code.length === 1) code = '0' + code
  if (!code) return BUREAUX_RAW.map(([id, , name, address]) => ({ id, name, address, wilaya: '' }))
  return BUREAUX_RAW.filter(([, wName]) => WILAYA_NAME_TO_CODE[wName] === code).map(
    ([id, wName, name, address]) => ({
      id,
      name,
      address,
      wilaya: WILAYA_NAME_TO_CODE[wName] ?? code,
    }),
  )
}

export { getBureauxByWilaya, BUREAUX_RAW, WILAYA_NAME_TO_CODE }
